language: ruby
cache: bundler
rvm:
- 2.1.2
- 2.2.5
- 2.3.1
- 2.3.4
- 2.4.1
gemfile:
- gemfiles/rails_4.gemfile
- gemfiles/rails_5_0.gemfile
- gemfiles/rails_5_2.gemfile
script:
- bundle exec rake spec
before_install:
- gem cleanup bundler
- gem install bundler -v 1.17.3
matrix:
  exclude:
  - rvm: 2.1.2
    gemfile: gemfiles/rails_5_0.gemfile
  - rvm: 2.1.2
    gemfile: gemfiles/rails_5_2.gemfile
notifications:
  email:
    on_success: never
  slack:
    secure: kcRMRU/epqsBn3n0McTz0RdGSR07xhyz5g6jOfufA1bRlmLsIQtIaeqeO0VLtcQFUd5JJ1Z2iVz9YdvbA0RLeXwI0ZS96g9NWZn1TFBk6zMM8/CN4kZcWcPKO9INbBMziRlF7lb039CRrusE0ei1YJLojPGWnsKITcS88rSX+Uq0wPDaN6nEzQbDU2HV3TBl31W0LlYYpcmz6Ju9HGVdU1NrA0DRbeV78YmUkyJ4v6p8pgOaKKx+oZidUQmjvBIuBcko9VayXnncg4NQZWG4c6A5keLEFHzgOpSEgu+NnHsTz5ILT2AtysNxC8UJ5dYc7hR/qXsB9Z6ZJjRc+oGTXq6j58f153AW+2R4Mtx7Lp2zg+JeqYO34riu8vnihBk5rNsuHNcz3+ipmePjBt6emmJVpMxleWs9JFpbxXm3JnaSQZtUqALqvs6ZL9gxxokQcy4xbD8BJFvhYpc3b2464JPJhK7LNDNobTv4LdG6m6KSzTnN//zNuE5hSQhMbjo9mnYWN7V9n3asi1EsEpIYqpjRJnlNVDwTdW0jJ7wUSNPdEvSL7g1lDqgJTUuNBh/stpXh6nA8Um5ZxU3cAuuX7VwnDqIdaw81UnkGIlYWBFYMMR2p03y7EaTMZafKWKEcS6LJsv7yIjtfHJgf45LkIHceEj++8JEOKItvDYWHOL4=
deploy:
  provider: rubygems
  api_key:
    # ninech-bot
    secure: XEI1NOR+bc+DTJE/PdF1I5E+Nfxb7Fngah2PtKsUBx1DMu1vavJubHieXK/GG2Zs03hDV4ZQl/YuvNLK2yfz/4HCAFsFjIayB7Bw6sXNFzWCLkFCpYTIIRsfSNSNA61ko+3ohYyiXSFj3sUMIuP0yhpWrIip17hzU3A0RJgVKEi4DWHgDgS4O32gKV5WUO6laLMS4BfDogY5RMEn92be7ReXnG+DHS3jnaXRHdtQuQWl1IZnE+B2LYY74NObRXN5riMFx1+6c6w9+dBwK3ljO6E7nOmrVrk/3XWT9oEK2bA67WGFTudmzVdXzQbfF/Cray1l5zFs/XFMmHNxdYlq9oY8neZqZU1+DYGFV9Wju2u/lyjIiccohFYeBS1ZshwIY+Oa05WIpkXkR5svO0SCxEbo5T2vML2saRuwYtIlI5cmMR8urdsU/PdW7GUWuBcH9TbcMuaaYJCuEFRsGBK/epOxwT2QbOl/loEr1PHeIyn0MHJiqVZslVNMaphOh+01yW2oZrh1PY43thT59l3uFWMVAhP9raWibHRHN9pPgipPFyAprFjbsgJtg/tIUJtHtue5ncyEDVe4KY4wbhr2qiyLJAoH9LOp/DkR10jnJHil8cMUD7mDCoTuM4n9XNFsdPaIiolpe2lxgMWwMnawQBqpfSqLl94QKn31OZKssZ0=
  gem: ordy
  on:
    tags: true
    repo: ninech/ordy
    condition: "$TRAVIS_RUBY_VERSION == 2.4.1"
  skip_cleanup: true
